version: '3.7'
services: 
  app:
    build:
      args:
          user: user1
          uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    extra_hosts:
      - "172.27.211.87:host-gateway"
    networks:
      - my-networks
    image: 'ws-mailing:1.1'
    container_name: app
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/mailing
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports: 
      - "3307:3306"
    networks:
    - my-networks
    environment:
      MYSQL_DATABASE: 'mailing'
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-lib:/var/lib/mysql
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "6378:6379"
    networks:
      - my-networks
    volumes:
      - redis-lib:/bitnami/redis/data
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    ports: 
      - "8025:8025"
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge
volumes:
  mysql-lib:
  redis-lib: