version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    networks:
      - my-networks
    image: 'ws-mailing:1.0'
    container_name: app
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    links:
      - db
    command: composer install && php artisan migrate
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports: 
      - "3307:3306"
    networks:
    - my-networks
    environment:
      MYSQL_DATABASE: 'mailing'
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-lib:/var/lib/mysql
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my-networks
    volumes:
      - redis-lib:/bitnami/redis/data
networks:
  my-networks:
    driver: bridge
volumes:
  mysql-lib:
  redis-lib: